matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - "3.7-dev"  # 3.7 development branch
    
# command to install dependencies

# command to run tests
script:
  - pytest
before_install:
  - pip install --user -r requirements.txt
